Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALd1Zf1ffYBjeD6dEiMKKx6Nkj7rNBGm


# Load necessary libraries
library(dplyr)
library(lubridate)  # For handling dates if needed
library(purrr)  # for map functions

# 1. Load the data
DMV_Data <- read.csv("/path/to/your/DMV_Data.csv")

# 2. Drop all columns except for the ones listed (keeping the necessary columns)
DMV_Data <- DMV_Data %>%
  select(
    Registration.Class,
    Vehicle.Identification.Number,
    Model.Year,
    Make.Code,
    Body.Type,
    Maximum.Gross.Vehicle.Weight,
    Fuel,
    Cylinders,
    Transaction,
    Registrant,
    City,
    Effective.Date,
    Registration.Expiration,
    Exported
  )

# 3. Check for missing values and drop rows with any missing values
DMV_Data <- na.omit(DMV_Data)  # Removes rows with any NA values

# 4. Correct misspelled city names in the City column
# Define the corrections for city names
corrections <- list(
  `Syracuse` = c('Syracuse', 'Syracus', 'Syr', 'Syracruse', 'Syracause', 'Syracusee', 'Syrascuse', 'Syrwcuse', 'Syrarcuse', 'Syracauese', 'Syracse', 'Syracise', 'Syracure', 'Syracuce', 'Syracuswe', 'Syracause', 'Syracues', 'Syracus', 'Syrarcuse', 'Syracrusee', 'Syracuse', 'Syr', 'Syraca', 'Syracusr'),
  `Liverpool` = c('Liverpool', 'Liverpol', 'Lverpool', 'Liverpoo', 'Liverpooll', 'Liverpooil', 'Liverpoll', 'Livberpool', 'Liverpoole', 'Lverpol', 'Liverpole', 'Liverypool', 'Liverppol', 'Lvrpool', 'Liveropol', 'Lpool'),
  `East Syracuse` = c('East Syracuse', 'East Syrcause', 'East Syracus', 'East Syr', 'East Syracse', 'East Syra', 'East Syruse', 'East Syrucus', 'East Syracsue', 'East Syrcause', 'East Syracue', 'East Syraucse', 'E Syracuse', 'East Sracuse', 'East Syracyse'),
  `Baldwinsville` = c('Baldwinsville', 'Baldwinville', 'Baldwinsvile', 'Baldwinville', 'Baldwnsville', 'Baldwainsville', 'Baldwainsvil', 'Baldwinsvill', 'Baldwinsvil', 'Baldwinvsille', 'Baldwinesville', 'Baldwensville', 'Baldwinsvile', 'Baldinville', 'Baldwnsivlle', 'Baldwinvlle'),
  `Manlius` = c('Manlius', 'Manilius', 'Manluus', 'Manluos', 'Manlious', 'Manliuos', 'Manlius', 'Manlius', 'Manllius', 'Manluis', 'Manulus', 'Manulous', 'Manulius'),
  `Chittenango` = c('Chittenango', 'Chittanango', 'Chittanngo', 'Chittinango', 'Chittennago', 'Chittenengo', 'Chittenago', 'Chittinengo', 'Chittnango', 'Chittenanngo', 'Chittenanago', 'Chittanago', 'Chittengo', 'Chittenang', 'Chittennango'),
  `Fayetteville` = c('Fayetteville', 'Fayettevile', 'Fayettevill', 'Fayettville', 'Fayeteville', 'Fayettville', 'Fayetville', 'Fyetteville', 'Fyatteville', 'Fayatteville', 'Fayetevill', 'Fayetevile', 'Faytteville', 'Fayettvill'),
  `Camillus` = c('Camillus', 'Cammillus', 'Camilus', 'Camiluss', 'Camilllus', 'Camiluls', 'Camillius', 'Camillous', 'Cmillus', 'Cmilus', 'Cammilus', 'Camilluss', 'Camillus', 'Cammiluss', 'Cammilius', 'Camullus'),
  `Pompey` = c('Pompey', 'Pompy', 'Pompei', 'Pompay', 'Pomphey', 'Pompie', 'Pompei', 'Pompae', 'Pompai', 'Pompay', 'Pompye', 'Pompy', 'Pomopey', 'Pomopei', 'Pompiey'),
  `Skaneateles` = c('Skaneateles', 'Skaneatles', 'Skaneatels', 'Skaneatless', 'Skanateles', 'Skaneatlees', 'Skaneatle', 'Skaneteles', 'Skanatele', 'Skaneatlee', 'Skneateles', 'Skanateles', 'Skanatelees', 'Skneatles')
)

# Function to correct city names based on the corrections list
apply_corrections <- function(city) {
  for (correct_name in names(corrections)) {
    if (city %in% corrections[[correct_name]]) {
      return(correct_name)
    }
  }
  return(city)  # Return original if not found in corrections
}

# Apply the corrections to the 'City' column
DMV_Data <- DMV_Data %>%
  mutate(City = map_chr(City, apply_corrections))

# Save the cleaned data
write.csv(DMV_Data, "/path/to/your/cleaned_DMV_Data.csv", row.names = FALSE)

# Print out a summary to confirm changes
summary(DMV_Data)